// Generated by CoffeeScript 1.6.1

/*
# 封装 Redis 连接进行封装
*/


(function() {
  var handleAuth, handleEnd, handleError, handleReady, handleReconnecting, logger, redis, settings;

  redis = require("redis");

  logger = require("../config/logger");

  settings = require("../config/settings");

  handleError = function(error) {
    return logger.error("[redis_util:handleError] " + error);
  };

  handleEnd = function() {
    return logger.info("[redis_util:handleEnd]");
  };

  handleReady = function() {
    var isRedisReady;
    isRedisReady = true;
    return logger.info("[redis_util:handleReady] Connected to Redis.");
  };

  handleReconnecting = function(info) {
    return logger.info("[redis_util:handleReconnecting] Reconnect to datastore... delay: " + info.delay + ", attempt: " + info.attempt);
  };

  handleAuth = function(error) {
    if (error) {
      return logger.error("[redis_util:handleAuth] " + error);
    } else {
      return logger.info("[redis_util:handleAuth] Connection authenticated.");
    }
  };

  exports.createClient = function() {
    var client;
    client = redis.createClient(settings.redisPort, settings.redisHost);
    client.debug_mode = settings.debug;
    client.on("ready", handleReady);
    client.on("error", handleError);
    client.on("end", handleEnd);
    client.on("reconnecting", handleReconnecting);
    if (settings.redisPassword) {
      client.auth(settings.redisPassword, handleAuth);
    }
    return client;
  };

}).call(this);
