// Generated by CoffeeScript 1.6.1
(function() {
  var redis;

  redis = require('../db/redis_util').createClient();

  redis.hmset("xiaosan", "name", "yangpengyuan", "age", 25, "gender", "male", function(error, result) {
    console.log("error: " + error);
    return console.log(result);
  });

}).call(this);
