// Generated by CoffeeScript 1.6.1
(function() {
  var StockIX, WindTalker, settings, stock_ix,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  WindTalker = require('./wind_talker');

  settings = require('../config/settings');

  StockIX = (function(_super) {

    __extends(StockIX, _super);

    function StockIX() {
      return StockIX.__super__.constructor.apply(this, arguments);
    }

    return StockIX;

  })(WindTalker);

  stock_ix = new StockIX('IX', settings.host, settings.port);

  process.on('message', function(msg) {
    console.log("[CHILD] RECEIVED " + msg);
    if (msg === 'start') {
      stock_ix.listen();
    }
    return process.send("[CHILD] process#" + process.pid + " copy " + msg + ".");
  });

  process.on('exit', function() {
    console.log('EXIT ....');
    process.send("[CHILD] process#" + process.pid + " exit.");
    return stock_ix.stop();
  });

  process.on('SIGTERM', function() {
    console.log('SIGTERM ....');
    process.send("[CHILD] process#" + process.pid + " terminated.");
    return process.exit(0);
  });

  process.stdin.on('data', function(msg) {
    return console.log("[CHILD] process#" + process.pid + " stdout: " + msg);
  });

  process.stderr.on('data', function(msg) {
    return console.log("[CHILD] process#" + process.pid + " stderr: " + msg);
  });

}).call(this);
