// Generated by CoffeeScript 1.6.1
(function() {
  var StockHK, WindTalker, settings, stock_hk,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  WindTalker = require('./wind_talker');

  settings = require('../config/settings');

  StockHK = (function(_super) {

    __extends(StockHK, _super);

    function StockHK() {
      return StockHK.__super__.constructor.apply(this, arguments);
    }

    StockHK.prototype.redisKey = function(ticker) {
      var key;
      if (ticker) {
        return key = "" + settings.redisNamespace + ":HK:" + ticker;
      } else {
        return null;
      }
    };

    return StockHK;

  })(WindTalker);

  stock_hk = new StockHK('HK', settings.host, settings.port);

  process.on('message', function(msg) {
    console.log("[CHILD][StockHK] RECEIVED " + msg);
    if (msg === 'start') {
      stock_hk.listen();
    }
    return process.send("[CHILD][StockHK] process#" + process.pid + " copy " + msg + ".");
  });

  process.on('exit', function() {
    console.log('EXIT ....');
    stock_hk.stop();
    return process.send("[CHILD][StockHK] process#" + process.pid + " exit.");
  });

  process.on('SIGTERM', function() {
    console.log('SIGTERM ....');
    process.send("[CHILD][StockHK] process#" + process.pid + " terminated.");
    return process.exit(0);
  });

}).call(this);
