// Generated by CoffeeScript 1.6.1
(function() {
  var StockSH, WindTalker, settings, stock_sh,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  WindTalker = require('./wind_talker');

  settings = require('../config/settings');

  StockSH = (function(_super) {

    __extends(StockSH, _super);

    function StockSH() {
      return StockSH.__super__.constructor.apply(this, arguments);
    }

    StockSH.prototype.running_schedule = function() {
      return console.log(settings.channels.sh);
    };

    return StockSH;

  })(WindTalker);

  exports.StockSH = StockSH;

  stock_sh = new StockSH('SH', settings.host, settings.port);

  process.on('message', function(msg) {
    console.log("child got " + msg);
    if (msg === 'start') {
      stock_sh.listen();
      console.log("child will start()");
    } else if (msg === 'stop') {
      stock_sh.stop();
      console.log("child will stop()");
    }
    return process.send("[CHILD] process#" + process.pid + " copy " + msg + ".");
  });

  process.on('exit', function() {
    return console.log("[CHILD] process#" + process.pid + " quit.");
  });

  process.stdout.on('data', function(msg) {
    return console.log("[CHILD] process#" + process.pid + " stdout: " + msg);
  });

  process.stderr.on('data', function(msg) {
    return console.log("[CHILD] process#" + process.pid + " stderr: " + msg);
  });

}).call(this);
