// Generated by CoffeeScript 1.6.1
(function() {
  var StockSH, WindTalker, settings, stock_sh,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  WindTalker = require('./wind_talker');

  settings = require('../config/settings');

  StockSH = (function(_super) {

    __extends(StockSH, _super);

    function StockSH() {
      return StockSH.__super__.constructor.apply(this, arguments);
    }

    StockSH.prototype.redisKey = function(ticker) {
      var key;
      if (ticker) {
        return key = "" + settings.redisNamespace + ":SH:" + ticker;
      } else {
        return null;
      }
    };

    return StockSH;

  })(WindTalker);

  stock_sh = new StockSH('SH', settings.host, settings.port);

  process.on('message', function(msg) {
    console.log("[CHILD][StockSH] RECEIVED " + msg);
    if (msg === 'start') {
      stock_sh.listen();
    } else if (msg === 'download') {
      stock_sh.downloadAndSave('SH');
    }
    return process.send("[CHILD][StockSH] process#" + process.pid + " copy " + msg + ".");
  });

  process.on('error', function(err) {
    console.log('[CHILD][SH] Internal Error #{err} Occured.');
    process.send(err);
    return process.exit(1);
  });

  process.on('exit', function() {
    console.log('EXIT ....');
    stock_sh.stop();
    return process.send("[CHILD][StockSH] process#" + process.pid + " exit.");
  });

  process.on('SIGTERM', function() {
    console.log('SIGTERM ....');
    process.send("[CHILD][StockSH] process#" + process.pid + " terminated.");
    return process.exit(0);
  });

}).call(this);
