// Generated by CoffeeScript 1.6.1
(function() {
  var StockSZ, WindTalker, settings,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  WindTalker = require('./wind_talker');

  settings = require('../config/settings');

  StockSZ = (function(_super) {

    __extends(StockSZ, _super);

    function StockSZ() {
      return StockSZ.__super__.constructor.apply(this, arguments);
    }

    StockSZ.prototype.running_schedule = function() {
      return console.log(settings.channels.sz);
    };

    return StockSZ;

  })(WindTalker);

}).call(this);
