// Generated by CoffeeScript 1.6.1
(function() {
  var StockIX, WindTalker, logger, settings, stock_ix,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  WindTalker = require('./wind_talker');

  settings = require('../config/settings');

  logger = require('../config/logger');

  StockIX = (function(_super) {

    __extends(StockIX, _super);

    function StockIX() {
      return StockIX.__super__.constructor.apply(this, arguments);
    }

    StockIX.prototype.keys_map = function() {
      var obj;
      return obj = {
        'IXCOZCA0': 'U-CO',
        'IXCOZSA0': 'U-BE',
        'IXCOZWA0': 'U-WH',
        'IXFXAUDUSD': 'AUDUSD',
        'IXFXEURGBP': 'EURGBP',
        'IXFXEURUSD': 'EURUDS',
        'IXFXGBPUSD': 'GBPUSD',
        'IXFXUSDBRL': 'USDBRL',
        'IXFXUSDCAD': 'USDCAD',
        'IXFXUSDCHF': 'USDCHF',
        'IXFXUSDCNY': 'USDCNY',
        'IXFXUSDINR': 'USDINR',
        'IXFXUSDJPY': 'USDJPY',
        'IXFXUSDKRW': 'USDKRW',
        'IXFXUSDMXN': 'USDMXN',
        'IXFXUSDRUB': 'USDRUB',
        'IXFXUSDSGD': 'USDSGD',
        'IXFXUSDTHB': 'USDTHB',
        'IXFXXAG': 'SLV',
        'IXFXXAP': 'PLT',
        'IXFXXAU': 'GLD',
        'IXNECLA0': 'OIL'
      };
    };

    StockIX.prototype.redisKey = function(ticker) {
      var corresponding_key, key;
      corresponding_key = this.keys_map[ticker];
      if (ticker === 'IXFXNZDUSD' || ticker === 'IXFXUSDTRY' || ticker === 'IXIXUDI') {
        corresponding_key = ticker;
      }
      corresponding_key = ticker;
      if (corresponding_key) {
        return key = "" + settings.redisNamespace + ":IX:" + corresponding_key;
      } else {
        return null;
      }
    };

    return StockIX;

  })(WindTalker);

  stock_ix = new StockIX('IX', settings.host, settings.port);

  process.on('message', function(msg) {
    console.log("[CHILD][StockIX] RECEIVED " + msg);
    if (msg === 'start') {
      stock_ix.listen();
    }
    return process.send("[CHILD][StockIX] process#" + process.pid + " copy " + msg + ".");
  });

  process.on('exit', function() {
    console.log('EXIT ....');
    stock_ix.stop();
    return process.send("[CHILD][StockIX] process#" + process.pid + " exit.");
  });

  process.on('SIGTERM', function() {
    console.log('SIGTERM ....');
    process.send("[CHILD][StockIX] process#" + process.pid + " terminated.");
    return process.exit(0);
  });

}).call(this);
