// Generated by CoffeeScript 1.6.1
(function() {
  var StockHK, WindTalker, settings,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  WindTalker = require('./wind_talker');

  settings = require('../config/settings');

  StockHK = (function(_super) {

    __extends(StockHK, _super);

    function StockHK() {
      return StockHK.__super__.constructor.apply(this, arguments);
    }

    StockHK.prototype.running_schedule = function() {
      return console.log(settings.channels.hk);
    };

    return StockHK;

  })(WindTalker);

}).call(this);
