// Generated by CoffeeScript 1.6.1
(function() {

  Date.prototype.yyyymmdd = function() {
    var dd, mm, yyyy;
    yyyy = this.getFullYear().toString();
    mm = (this.getMonth() + 1).toString();
    dd = this.getDate().toString();
    return "" + yyyy + "-" + mm + "-" + dd;
  };

}).call(this);
