// Generated by CoffeeScript 1.6.1
(function() {
  var Iconv, buf_length, fs, os, raw_buf_length, reserved_bytes_len, zlib;

  fs = require('fs');

  os = require('os');

  zlib = require('zlib');

  Iconv = require('iconv').Iconv;

  console.log("The CPU endian is " + (os.endianness()));

  buf_length = 0;

  reserved_bytes_len = 4;

  raw_buf_length = 0;

  fs.open(__dirname + "/../../data/wsSample.wsz", 'r', function(err, fd) {
    var buf;
    buf = new Buffer(4);
    buf.fill(0);
    return fs.read(fd, buf, 0, reserved_bytes_len, 0, function(err, bytesRead, buf) {
      buf_length = buf.readUInt32LE(0);
      return fs.read(fd, buf, 0, reserved_bytes_len, 0 + 4, function(err, bytesRead, buf) {
        var encrypt_data;
        raw_buf_length = buf.readUInt32LE(0);
        console.log("buff length: " + buf_length);
        console.log("raw buff length: " + raw_buf_length);
        encrypt_data = new Buffer(raw_buf_length);
        return fs.read(fd, encrypt_data, 0, raw_buf_length, 0 + 4 + 4, function(err, bytesRead, buf) {
          return zlib.inflate(encrypt_data, function(error, result) {
            return console.log(result.toString('utf-8', 0, result));
          });
        });
      });
    });
  });

}).call(this);
