// Generated by CoffeeScript 1.6.1
(function() {
  var fs, os;

  fs = require('fs');

  os = require('os');

  console.log("The CPU endian is " + (os.endianness()));

  fs.open("/tmp/a.txt", 'r', function(err, fd) {
    var buf;
    buf = new Buffer(30);
    buf.fill(0);
    return fs.read(buf, 0, 30, 0, function(err, bytesRead, buffer) {
      return console.log(buffer.toString('ascii'));
    });
  });

}).call(this);
