// Generated by CoffeeScript 1.6.1
(function() {
  var Iconv, bufferpack, fs, os;

  fs = require('fs');

  os = require('os');

  Iconv = require('iconv').Iconv;

  bufferpack = require('bufferpack');

  console.log("The CPU endian is " + (os.endianness()));

  fs.open(__dirname + "/../../data/wsSample.dat", 'r', function(err, fd) {
    var buf;
    buf = new Buffer(156);
    buf.fill(0);
    return fs.read(fd, buf, 0, 156, 0, function(err, bytesRead, buf) {
      return console.log(buf.toString('utf8'));
    });
  });

}).call(this);
